/**
 * Registry Generator - Auto-generates Next.js plugin registry from database
 *
 * This bridges the gap between dynamic backend plugins and Next.js static imports.
 * When plugins are activated/deactivated, this regenerates the registry file.
 */

const fs = require('fs');
const path = require('path');
const master = require('mastercontroller');

class RegistryGenerator {
  constructor() {
    this.registryPath = path.join(__dirname, '../../../../nextjs-app/plugins/registry.js');
  }

  /**
   * Generate the static plugin registry from registered views
   * This is called after plugin activation/deactivation
   */
  generateRegistry() {
    try {
      // Get the pluginLoader instance from master
      const pluginLoader = master.requestList.pluginLoader;

      if (!pluginLoader) {
        console.error('⚠ pluginLoader not found in master, cannot generate registry');
        return;
      }

      // Get all registered views
      const registeredViews = pluginLoader.getRegisteredViews();
      const viewsArray = Array.from(registeredViews.values());

      if (viewsArray.length === 0) {
        console.log('  ℹ No views registered, generating empty registry');
      }

      const imports = [];
      const registryEntries = [];

      viewsArray.forEach((view) => {
        const componentName = `Plugin_${this.sanitizeComponentName(view.slug)}`;

        // The importPath already includes 'plugins/...' from pluginLoader
        // We just need to add @/ for Next.js alias
        const importPath = `@/${view.importPath.replace(/\.js$/, '')}`;

        imports.push(`import ${componentName} from '${importPath}';`);
        registryEntries.push(`  '${view.slug}': ${componentName},`);
      });

      const fileContent = `/**
 * Auto-Generated Plugin Registry
 * Generated: ${new Date().toISOString()}
 *
 * This file is automatically generated when plugins are activated/deactivated.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

${imports.length > 0 ? imports.join('\n') : '// No plugins registered'}

export const pluginRegistry = {
${registryEntries.length > 0 ? registryEntries.join('\n') : '  // No views registered'
}
};

/**
 * Get a plugin component by slug
 * @param {string} slug - The view slug to look up
 * @returns {Component|null} The component or null if not found
 */
export function getPluginComponent(slug) {
  return pluginRegistry[slug] || null;
}
`;

      // Ensure the plugins directory exists
      const pluginsDir = path.dirname(this.registryPath);
      if (!fs.existsSync(pluginsDir)) {
        fs.mkdirSync(pluginsDir, { recursive: true });
      }

      fs.writeFileSync(this.registryPath, fileContent, 'utf8');
      console.log(`  ✓ Generated plugin registry with ${viewsArray.length} view(s)`);

      return {
        success: true,
        viewCount: viewsArray.length
      };

    } catch (error) {
      console.error('  ✗ Error generating plugin registry:', error.message);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Sanitize a slug to create a valid JavaScript component name
   * Example: 'rag-settings' -> 'RagSettings'
   */
  sanitizeComponentName(slug) {
    return slug
      .split(/[-_]/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
  }
}

// Export singleton instance
module.exports = new RegistryGenerator();
