/**
 * Auto-Generated Plugin Registry
 * Generated: 2025-11-06T23:36:24.666Z
 *
 * This file is automatically generated when plugins are activated/deactivated.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

import Plugin_RagSettings from '@/plugins/rag-plugin/nextjs/pages/admin/rag/settings/page';
import Plugin_RagDocuments from '@/plugins/rag-plugin/nextjs/pages/admin/rag/documents/page';
import Plugin_PluginsInstalled from '@/plugins/plugin-plugin/nextjs/pages/admin/plugins/installed/page';

export const pluginRegistry = {
  'rag-settings': Plugin_RagSettings,
  'rag-documents': Plugin_RagDocuments,
  'plugins-installed': Plugin_PluginsInstalled,
};

/**
 * Get a plugin component by slug
 * @param {string} slug - The view slug to look up
 * @returns {Component|null} The component or null if not found
 */
export function getPluginComponent(slug) {
  return pluginRegistry[slug] || null;
}
