/**
 * AUTO-GENERATED PLUGIN LOADER
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * Generated by: components/plugins/app/core/loaderGenerator.js
 * Generated at: 2025-11-10T23:13:41.195Z
 * 
 * This file statically imports plugin components so Next.js can
 * resolve all dependencies (including next/navigation) at build time.
 */

import Plugin_0 from "../plugins/rag-plugin/admin/rag/settings/page";
import Plugin_1 from "../plugins/rag-plugin/admin/rag/documents/page";
import Plugin_2 from "../plugins/rag-plugin/client/KnowledgeBaseSidebar";
import Plugin_3 from "../plugins/tokens-plugin/admin/tokens/settings/page";
import Plugin_4 from "../plugins/tokens-plugin/admin/tokens/analytics/page";

/**
 * Plugin component registry
 * Maps component names to imported components with metadata
 */
export const pluginComponents = {
  "RagSettingsPage": {
    component: Plugin_0,
    pluginName: "rag-plugin",
    metadata: {
          "description": "RAG Settings admin page",
          "usage": "admin-view",
          "viewSlug": "rag-settings"
    }
  },
  "RagDocumentsPage": {
    component: Plugin_1,
    pluginName: "rag-plugin",
    metadata: {
          "description": "RAG Documents admin page",
          "usage": "admin-view",
          "viewSlug": "rag-documents"
    }
  },
  "KnowledgeBaseSidebar": {
    component: Plugin_2,
    pluginName: "rag-plugin",
    metadata: {
          "description": "Document management sidebar for chat interface",
          "usage": "sidebar-left",
          "features": [
                "document-list",
                "workspace-creation",
                "document-upload",
                "rag-settings"
          ]
    }
  },
  "TokenSettingsPage": {
    component: Plugin_3,
    pluginName: "tokens-plugin",
    metadata: {
          "description": "Token Settings admin page",
          "usage": "admin-view",
          "viewSlug": "tokens-settings"
    }
  },
  "TokenAnalyticsPage": {
    component: Plugin_4,
    pluginName: "tokens-plugin",
    metadata: {
          "description": "Token Analytics admin page",
          "usage": "admin-view",
          "viewSlug": "tokens-analytics"
    }
  }
};

/**
 * Get a plugin component by name
 * @param {string} name - Component name
 * @returns {Object|null} Component info or null if not found
 */
export function getPluginComponent(name) {
  return pluginComponents[name] || null;
}

/**
 * Get all plugin components for a specific usage type
 * @param {string} usage - Usage type (e.g., "sidebar-left")
 * @returns {Array} Array of component info objects
 */
export function getComponentsByUsage(usage) {
  return Object.entries(pluginComponents)
    .filter(([_, info]) => info.metadata?.usage === usage)
    .map(([name, info]) => ({ name, ...info }));
}

/**
 * Get all registered component names
 * @returns {Array<string>} Array of component names
 */
export function getComponentNames() {
  return Object.keys(pluginComponents);
}
